import = ["~/.config/alacritty/cyberdream.toml"]

[window]

opacity = 0.7
blur = true

padding.x = 10
padding.y = 10

decorations = "Buttonless"

[colors.primary]
background = "#030b16"
foreground = "#e9def2"

[font]

normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

size = 12.0
